name: sync
on:
  workflow_dispatch:
  schedule:
    - cron: "40 19 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 10

      - uses: Craftyawesome/rebase-upstream-action@master
        with:  # all args are optional
          upstream: j-hc/revanced-magisk-module
          branch: main
